### ISSUE TITLE
Scrollbar still remains when removing all the items from the array

### ISSUE THREAD

**Issue by GustavoFring** [kamilkp/angular-vs-repeat#103]
How to reproduce:
- take the demo http://kamilkp.github.io/angular-vs-repeat/
- in the form, set 0 as array size
- apply
![capture-20160129-182212](https://cloud.githubusercontent.com/assets/16961193/12682790/b48f559e-c6b5-11e5-965e-94b2fd047cd1.png)

**Comment by nitinju** [comment]
+1
