### ISSUE TITLE
table scroll bar height error

### ISSUE THREAD

**Issue by clijiac** [kamilkp/angular-vs-repeat#110]
just see the demo [http://kamilkp.github.io/angular-vs-repeat/#?tab=9](http://kamilkp.github.io/angular-vs-repeat/#?tab=9)

the `<tr class="vs-repeat-after-content" style="width: 100%; min-height: 29460px;"></tr>` will not have any effect. for `tr` we may just use height

**Comment by kamilkp** [comment]
Good catch. Thanks. Fixed in v1.1.6

**Comment by clijiac** [comment]
wow. quickly response :+1:   
thank you!
