### ISSUE TITLE
Angular2 support

### ISSUE THREAD

**Issue by iBasit** [kamilkp/angular-vs-repeat#125]
will there be angular2 support anytime soon?

**Comment by kamilkp** [comment]
Yes, although its gonna be in its own repository. I already started working on it [here](https://github.com/kamilkp/ng2-vs-for). Stay tuned!

**Comment by iBasit** [comment]
Looking forward to using on our ionic mobile app 👍

**Comment by kamilkp** [comment]
There is a pretty stable version on https://github.com/kamilkp/ng2-vs-for now. There are no docs nor a proper demo page yet, but you can figure out the api from the `temp/boot.ts` file with an example app.
