### ISSUE TITLE
Safari scrolling

### ISSUE THREAD

**Issue by alevinru** [kamilkp/angular-vs-repeat#132]
Everything's fine with Chrome, but Safari don't apply correctly height to vs-repeat-after-content and vs-repeat-beforer-content. Because of this, scrolling is not as smooth as should be. Using an inspector I've noticed that set height is accurate at the right pane of inspector, but always the same in the dom (highlighted row)

<img width="1212" alt="screen shot 2016-05-16 at 08 53 41" src="https://cloud.githubusercontent.com/assets/834503/15283354/7db93566-1b52-11e6-8c3e-5020a3efaa9d.png">

**Comment by jweinstein92** [comment]
+1

**Comment by alevinru** [comment]
@jweinstein92 use style -webkit-overflow-scrolling: touch; for scroll-parent element
