### ISSUE TITLE
IE white lines for big array

### ISSUE THREAD

**Issue by fantastik78** [kamilkp/angular-vs-repeat#142]
Hi,

I tried your plugin using the demo page with 250 000 lines, and in Internet Explorer 11 only half (more or less) is displayed, then it's only white rows 
![250k-angular-vs-repeat](https://cloud.githubusercontent.com/assets/956167/17592688/84cf0fda-5fe3-11e6-9bf5-72812b4b66cc.PNG)

Is it a known bug ? Is there limitation on IE11 ?

Thanks.

**Comment by fantastik78** [comment]
Well it seems that IE11 only allows a div to be a certain height and do not render what comes out...
http://stackoverflow.com/questions/7719273/determine-maximum-possible-div-height

**Comment by meenakshijha** [comment]
@fantastik78  I am facing the same issue in IE 11 (works fine in chrome). What exactly did you do to solve this issue?

**Comment by fantastik78** [comment]
@meenakshijha we ended up doing a pagination of the result.
