### ISSUE TITLE
ng-repeat on a non-div element doesn't seem to work

### ISSUE THREAD

**Issue by rinogo** [kamilkp/angular-vs-repeat#150]
There may be something else going on here, but in my app, using `vs-repeat` to enclose an `ng-repeat` on a non-div (e.g. `a`) element doesn't seem to work.

Doesn't work (nothing is displayed):
```
	<div vs-repeat>
		<a ui-sref="tab.view-subscriber({id: subscriber.id})" ng-repeat="subscriber in ctrl.subscribers['A']">
			<div>etc...</div>
		</a>
	</div>

```

Works
```
	<div vs-repeat>
		<div ui-sref="tab.view-subscriber({id: subscriber.id})" ng-repeat="subscriber in ctrl.subscribers['A']">
			<div>etc...</div>
		</div>
	</div>

```

Is this a bug, by design, or am I doing something wrong?

**Comment by stefchri** [comment]
Could this not be because of the css display property difference between a and div?

**Comment by rinogo** [comment]
Wow, I think that did it!

Switching back from `<div>` to `<a>` caused the problem to appear again.  Not only did the elements not appear in the browser, but they didn't even show up in the DOM.

In this broken state, adding `a { display: block; }` solved the problem!  I would have never guessed to do that since the elements weren't even appearing in the DOM.  I'm guessing vs-repeat somehow only processes block elements and simply ignores others?

**Comment by rinogo** [comment]
Would it be a good idea to add some clarification to [`Readme.md`](https://github.com/kamilkp/angular-vs-repeat/blob/master/README.md)?

**Comment by stefchri** [comment]
@rinogo This will be because of the required known sizes of the repeated elements I think.
