### ISSUE TITLE
Keyboard control lost when elements with focus are removed from dom

### ISSUE THREAD

**Issue by kentcdodds** [kamilkp/angular-vs-repeat#17]
I think a solution to this would be to check if an element has focus when it's removed from the dom and if it does, set focus on the parent. Here's an example of my problem:

![example](http://cl.ly/XNw6/key-issues.gif)

**Comment by kamilkp** [comment]
This is because the focused elements gets removed from the DOM. The directive would have to programatically focus another element in the list when it detects that it removes a focused element. I'll look into that.

**Comment by Aknilam** [comment]
I found the solution:
you should add `tabindex="0"` to scrollable container.
