### ISSUE TITLE
ionic 1.x doesn't work (bug report)

### ISSUE THREAD

**Issue by vahidvdn** [kamilkp/angular-vs-repeat#173]
When I want to run this project on ionic app, it doesn't work fine. Here is the [codepen ](https://codepen.io/sdns/pen/NvKBGR)of this bug demonstration.

Just clean `ionic` from module dependency in first line (then it works):

```
angular.module('ionicApp', ['ionic', 'vs-repeat'])
```

Any idea?

**Comment by vahidvdn** [comment]
I made some changes in styles and now works like a charm. See new codepen [here](https://codepen.io/sdns/pen/VzZJxw).

**Comment by acollazomayer** [comment]
@vahidvdn hi im having a problem with ionic, only the first two elements are rendering with your code. Do you know why might this happen
