### ISSUE TITLE
How to escape the # character

### ISSUE THREAD

**Issue by richhosek** [kamilkp/angular-vs-repeat#184]
If I have the # character in the HTML that is being repeated, the  plug-in tries to interpret it as the start of dynamic value. How can I indicate that I just want to display #?

**Comment by itanex** [comment]
@richhosek this isn't an issue with this library, it is more of an Angular or HTML interpretation process; the process is attempted to interpret the hash sign as HTML, if you want it to be interpreted as text, you need to use the html character entity for it.

>   `&num;` // renders in html as #

A great place for a quick reference is: https://brajeshwar.github.io/entities/

**Comment by kamilkp** [comment]
Exactly.
