### ISSUE TITLE
Some times in Chrome scroll handler are called continuously

### ISSUE THREAD

**Issue by dardino** [kamilkp/angular-vs-repeat#186]
I scroll one time with mouse wheel, the scroll event does not stop until reach the end of list.
I have this problem only in Chrome and not in all cases.
I tested the same page in Edge and Firefox and it works fine.
What I need to know ? I don't understand the difference between working case and not working case.
What can it be?

I have fixed height for items and fixed height for scrollarea

**Comment by dardino** [comment]
[vs-repeat-bug.zip](https://github.com/kamilkp/angular-vs-repeat/files/1719377/vs-repeat-bug.zip)
This is a plunker for test with Chrome:
[http://plnkr.co/edit/EsrysbLVE1yKyjt3JUkL?p=preview](http://plnkr.co/edit/EsrysbLVE1yKyjt3JUkL?p=preview)

**Comment by liu351** [comment]
I read you can add overflow-anchor: none to your .main css class. Worked for my project

**Comment by napernik** [comment]
Thanks, upgrading from 1.1.7 to 1.1.11 and using "overflow-anchor: none" on the scroll-able element solved the problem!

There seem to be an infinite recursive call, a side effect of which is raising the "scroll" event repeatedly. Here's a part of the call stack:

![image](https://user-images.githubusercontent.com/1391705/37286618-bf5fd42c-2602-11e8-8c15-67e202029c36.png)

**Comment by kerryj89** [comment]
Just want to point out that mine was solved by removing $index in `ng-repeat` - this somehow caused mine to continuously scroll down when loading in new items; solved by not using it: https://github.com/kamilkp/angular-vs-repeat/issues/95
