### ISSUE TITLE
double question marks raising syntax error in the 2.0.6

### ISSUE THREAD

**Issue by Liooo** [kamilkp/angular-vs-repeat#190]
for example on this line 
https://github.com/kamilkp/angular-vs-repeat/blob/master/src/angular-vs-repeat.js#L95

Other lines have `??` as well, is this a valid js syntax that I don't know, or you were just back from C# or something?

**Comment by kamilkp** [comment]
It is valid but currently only with babel. https://github.com/tc39/proposal-nullish-coalescing

**Comment by Liooo** [comment]
oh didn't know that thanks, then I think it's bower.json's problem. `main` entity should be `dist/angular-vs-repeat.min.js` instead of `src/angular-vs-repeat.js`. even latest stable chrome doesn't accept `??` syntax yet, so.

**Comment by harshpuidev** [comment]
I also had the same issue pointing it to dist/angular-vs-repeat solved it but i have used vs-repeat at multiple places and now i see only 1st element out of thousand.

In a viewport i can display about 15 element but currently i see only one and then when i trigger a scroll it display all elements.
i am using angular 1.5.9

**Comment by kamilkp** [comment]
Yeah, it’s a problem with bower.json indeed.

Kamil Pękala
