### ISSUE TITLE
Is it possible to get value of $index similar to case without vs-repeat? 

### ISSUE THREAD

**Issue by shastri9999** [kamilkp/angular-vs-repeat#20]
Since vs-repeat keeps only necessary elements in DOM it is expected that value of $index will be different from the case of without vs-repeat. 

See the jsbin example [here](http://jsbin.com/durupisinizu)

But I have a peculiar use-case where in the rendered table is sorted and/or filtered and I need to get $index value as shown in without vs-repeat example. 

To give you details about use-case, the check-boxes in example can be multi-selected. i.e. I select a particular check-box hold <kbd>Shift</kbd> and then scroll down and check another check-box. Doing so should select all the check-boxes in between rows. Now for this to be implemented, I will want to know actual index values as in case of without vs-repeat.

Is there a workaround to get $index values similar to without vs-repeat? I tried to derive it using totalHeight and scrollTo values, but is there a more reliable way?

**Comment by SaurabhSharma45** [comment]
Me too was silly :)
