### ISSUE TITLE
ng-repeat-start

### ISSUE THREAD

**Issue by jcq** [kamilkp/angular-vs-repeat#23]
Is there a way to get this to work with elements that are part of a ng-repeat-start / ng-repeat-end block? If I'm understanding the code correct, it's looking for "ng-repeat" specifically, and it bombs out if it doesn't find that specific attribute with this error (line 99 of unminified v1.0.0-rc5 js):
`TypeError: Cannot read property '1' of null`

**Comment by pulkitsinghal** [comment]
I don't know enough to submit a PR but just want to say `+1` as it would be very useful

**Comment by kamilkp** [comment]
Works since angular-vs-repeat v1.0.1-beta.2
