### ISSUE TITLE
Use with grid-layout

### ISSUE THREAD

**Issue by yoohahn** [kamilkp/angular-vs-repeat#24]
Is there any plans to make it work with a grid-layout on the repeated items?

Seems like the translationY breaks the grid;
http://codepen.io/anon/pen/VYvmQN?editors=100

**Comment by kamilkp** [comment]
This ain't easy as it would have to calculate how many elements ft in a row, and if those elements ain't equal in size it would get even worse (not only hard to implement but also affecting performance). You could obtain something grid-like by nesting ng-repeat within vs-repeat: have vs-repeat render rows, and within each row render 3 items using ng-repeat.
