### ISSUE TITLE
vs-repeat vs ng-repeat with one-time binding

### ISSUE THREAD

**Issue by rafis** [kamilkp/angular-vs-repeat#27]
I'm using ngInfiniteScroll. After loading next portion of list with $http I'm placing it not directly to items array, but instead in subarray:

    $http.get('list', {
        params: {
            offset: this.offset
        }
    }).then(function(data) {
        this.items = this.items.concat([data.data.items]);
        this.offset++;
        this.busy = false;
    }).bind(this));

In view I'm using one-time binding on subarray:

    <div class="page-content" infinite-scroll="list.nextPage()" infinite-scroll-disabled="list.busy" infinite-scroll-distance="1">
        <div class="row" ng-repeat="portion in list.items">
            <div class="col-md-12" ng-repeat="item in ::portion">
            </div>
        </div>
        <div ng-show="list.busy">Loading items...</div>
    </div>

I think this trick makes vs-repeat benefitless for my case? Will I benefit from using vs-repeat?

**Comment by kamilkp** [comment]
You won't get so many elements rendered into the DOM (which takes some time). But I don't think that current version of vs-repeat even supports the one time binding syntax.
