### ISSUE TITLE
Angular version?

### ISSUE THREAD

**Issue by sheymann** [kamilkp/angular-vs-repeat#31]
Hello,

Which version of Angular is supported?

**Comment by kamilkp** [comment]
I have originally implemented this using angular 1.2.16. But it should work just fine with 1.3. If you have any problems running it on 1.3 let me know.

**Comment by benjamincharity** [comment]
I can't seem to get this to work on 1.3.15. Consistently get `Error: null is not an object (evaluating 'expressionMatches[1]')`.

I also noticed that the gh-pages branch demo doesn't seem to work with `1.3.15`, `1.3.0` or 1.3.1`. 

Further, I can't seem to even get `1.2.16` working in a plunkr...am I missing something on the set up?

Plunkr with Angular 1.2.16: http://plnkr.co/edit/jsDy4l?p=preview
Plunkr with Angular 1.3.15: http://plnkr.co/edit/xP1EhZ?p=preview

**Comment by kamilkp** [comment]
You need to inclue the module. First line in your `app.js` should look sth like that:
````
var app = angular.module('plunker', ['vs-repeat']);
````

**Comment by benjamincharity** [comment]
Jeez... sorry for being 'that guy'...

Still get the same error message as above in my project, but at least I know that it's working on `1.3.x`.

Thanks for the quick response!
