### ISSUE TITLE
Ng-repeat with starting point available?

### ISSUE THREAD

**Issue by STheFox** [kamilkp/angular-vs-repeat#34]
Hello!

First of all, thanks for this wonderful directive, helped me a lot with my DOM memory management.
But I have a question, regarding the starting point of where the view gets rendered.
Is there a way I can set a starting point where my view gets rendered?

Let's say our ng-repeat has to iterate over a 100 elements in a scrollable view, now the elements get rendered from 1 to 100 on the screen. Well, I want to see the elements starting from 20 visible, and 1-19 visible when I scroll up. Is there a way I can do this?

Thanks!

**Comment by karna41317** [comment]
any solution for this case ? ,i need too.

**Comment by BlackMan82** [comment]
Does #32 contain functionality that you want?

**Comment by kamilkp** [comment]
I think so, and it will be merged very soon.

**Comment by kamilkp** [comment]
Merged
