### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by sniperman111** [kamilkp/angular-vs-repeat#39]
Please if you can help me i am always find this error Cannot read property '1' of null and i don't know why

**Comment by kamilkp** [comment]
Do you maybe use an object as a right hand side in your `ng-repeat` (instead of an array)? Otherwise can you create a sample fiddle for me?

**Comment by tamlyn** [comment]
Is the `vs-repeat` attribute on the direct parent of the element with `ng-repeat`? Check the DOM tree to make sure some extra element hasn't been added in between (e.g. `tbody` between `table` and `tr`).

**Comment by sniperman111** [comment]
<div vs-repeat>
		<div ng-repeat="value in ['1','2','3','4']">
			{{value}}
		</div>
	</div>

**Comment by sniperman111** [comment]
div vs-repeat
		div ng-repeat="value in ['1','2','3','4']"
			{{value}}
		/div
	/div

**Comment by sniperman111** [comment]
i used it like that and still have the same problem

**Comment by kamilkp** [comment]
can you make a jsfiddle/plunkr?

**Comment by jetpackjarrett** [comment]
@sniperman111 did you resolve this issue? how?

**Comment by faheemhameed** [comment]
I got the same issue when I use the ng-repeat as below:

`<tr ng-repeat="(ind, rrRow) in row.roleRoom">`

It was resolved when I changed the above to below:

`<tr ng-repeat="rrRow in row.roleRoom">`

**Comment by SajShuuya** [comment]
Please support index in:
<tr ng-repeat="(index, rrRow) in row.roleRoom">
It is not working as @faheemhameed  mentioned.
