### ISSUE TITLE
iOS inertial scrolling does not work

### ISSUE THREAD

**Issue by that1guy** [kamilkp/angular-vs-repeat#40]
Are there any solutions to get inertial scrolling working on iOS?

This is a common workaround to the inertial scroll issue when overflow-y scrolling in a container, but this does not work with vs-repeat.  The elements will only render after the momentum scroll has come to a complete stop.

You can observe this behavior here by swiping quick on your iOS device.
````
http://kamilkp.github.io/angular-vs-repeat/#?tab=2
````

Love your plugin and would be awesome if you knew solution for this!

**Comment by kamilkp** [comment]
I've noticed it on my iPhone. Sadly the reason for this is that the iOS Safari triggers the `scroll` event only **after** the inertia stops. IMHO this qualifies for a bug report to Apple. Try hooking up a `scroll` event handler with a console.log and observe on your console when the events get triggered. Compare it to how the scroll events are being triggered on a Mac OSX browser. I can't think of any solution for that.

**Comment by that1guy** [comment]
vs-excess could partly workaround this issue, no?  I only ask because vs-excess isn't working for me (probably because I have an ng-repeat inside the vs-repeat?).

**Comment by kamilkp** [comment]
On what iOS were you testing this? I just tested on iOS 8.3 and it actually works, so it seems like Apple has fixed that :)
