### ISSUE TITLE
Cannot use `data-*` format for ng-repeat.

### ISSUE THREAD

**Issue by benjamincharity** [kamilkp/angular-vs-repeat#42]
Using `data-ng-repeat` rather than `ng-repeat` seems to break the plugin on lines [96-100](https://github.com/kamilkp/angular-vs-repeat/blob/master/src/angular-vs-repeat.js#L96-L100).

[Plunkr](http://plnkr.co/edit/xP1EhZ?p=preview)

Not a huge issue, but it definitely tripped me up for a minute.

**Comment by kamilkp** [comment]
closed via 7445e1e
