### ISSUE TITLE
Cannot read property '1' of undefined in updateInnerCollection

### ISSUE THREAD

**Issue by Raidok** [kamilkp/angular-vs-repeat#43]
I was looking for a library to make a horizontally scrollable box automatically scroll the active element into view and this here seemed like a great candidate for this task. Unfortunately I cannot seem to get it working.

[See Plunker](http://plnkr.co/edit/rAT1OzZunJFsXjDVttNd?p=preview)

The following error is logged when opening the page and similar ones when navigating with the buttons below the scrollable area:

    TypeError: Cannot read property '1' of undefined
        at updateInnerCollection (angular-vs-repeat.js:454)
        at reinitialize (angular-vs-repeat.js:334)
        at Object.fn (angular-vs-repeat.js:153)
        at n.$digest (angular.js:14308)
        at n.$apply (angular.js:14571)
        at HTMLAnchorElement.<anonymous> (angular.js:21571)
        at HTMLAnchorElement.c (angular.js:3032)

I am using the latest version from the master branch (f57eaa18eb).

It seems like it fails due to the $scope.sizesCumulative and/or $scope.sizes fields do not exists and I cannot seem to figure out why or how can I get them to work.

This seems to be a fairly new functionality and there aren't any examples around yet so maybe somebody can tell me where have I gone wrong?

Thanks!

Raido

**Comment by kamilkp** [comment]
This is a but in `vs-scroll-settings` functionality. Without it it works fine. I wrote about this but in the #32 PR conversation. Maybe the author know how to fix it fast.

**Comment by BlackMan82** [comment]
Fixed in #44. See [plunker](http://plnkr.co/hVwDoaxzJuCL3eGE0voc).
