### ISSUE TITLE
Firefox&Performance: When scrolling with mousewheel the scrolling is slower

### ISSUE THREAD

**Issue by mato75** [kamilkp/angular-vs-repeat#50]
When scrolling in Firefox, there is a performance issue. When scrolling, the scroll amount is smaller then native scrolling.

It is present on demo page.

**Comment by kamilkp** [comment]
Ok, and tell me please what OS are you testing this on?

**Comment by mato75** [comment]
Mac OS.

**Comment by mato75** [comment]
New version fixes this issue.

**Comment by Ins87** [comment]
Hey,
This problem still exists with my mac and firefox combo.

But if I remove these lines, everything is fine
```
if (isMacOS) {
   $scrollParent.on(wheelEventName, wheelHandler);
}
```  

Demo page is also slow
