### ISSUE TITLE
vsScrollParent: window

### ISSUE THREAD

**Issue by mato75** [kamilkp/angular-vs-repeat#51]
Nothing is appended when using window as vsScrollParent.

**Comment by kamilkp** [comment]
jsfiddle?

**Comment by mato75** [comment]
http://jsbin.com/laqelekada/2/edit

and put vs-scroll-parent="window" in tbody.

**Comment by kamilkp** [comment]
Thanks for catching it, there was a bug indeed. Your fiddle works now. Note that if you set scroll parent to window you shouldn't fix the height of the tbody

**Comment by mato75** [comment]
http://jsbin.com/qeloxiwupe/2/edit?html,css,js,output

It still doesn't work, because now scrolling is not working.

**Comment by kamilkp** [comment]
Check not [http://jsbin.com/mobipezehi/1/edit?html,css,js,output](http://jsbin.com/mobipezehi/1/edit?html,css,js,output)

**Comment by mato75** [comment]
It looks good, was the lib or my example?

**Comment by kamilkp** [comment]
Two bugs on my part. Second one only occured with `track by $index` only so thanks for catching it.
