### ISSUE TITLE
Removing item from list doesn't recalculate translateY

### ISSUE THREAD

**Issue by Avi-mcqueen** [kamilkp/angular-vs-repeat#54]
My code : 

`<div class="items-list" id="tableSearchResults" data-auto-Scroll-Table vs-repeat="85" vs-excess="5">`
        `<div class="request-row" ng-repeat="request in appData.favoriteDiamonds" ng-click="showItemDetails(request)">`

```
$scope.removeDiamondFromFavorites = function(diamond){
        if($scope.appData.favoriteDiamonds.indexOf(diamond) != -1){
            var index = $scope.appData.favoriteDiamonds.indexOf(diamond);
            $scope.appData.favoriteDiamonds.splice(index, 1);
        }
    }
```

When i remove item from list, it is also removed from the view and DOM element also removed from the view, but calculations (translateY) for the rest elements are not recalculated..

```
Example : 
had originally 4 items,
deleted item number 2, result : 

item1 - translateY(0) - wright
item2 - translateY(170) - wrong, must be 85
item3 - translateY(265) - wrong, must be 170
```
Any thoughts?

**Comment by kamilkp** [comment]
You need to broadcast 'vsRepeatTrigger' event

**Comment by Avi-mcqueen** [comment]
Thank you for fast reply.
I did try broadcast:
`$rootScope.$broadcast('vsRepeatTrigger');`
The call is activated, but no success..
I need to go forward in navigation and return back, for recalculation to be done.

**Comment by kamilkp** [comment]
What version of the lib are you using. Try latest

**Comment by Avi-mcqueen** [comment]
Using v1.0.0-rc9

**Comment by Avi-mcqueen** [comment]
Updated just now to rc10, 
Same problem

**Comment by kamilkp** [comment]
You need to create a sample demo on jsfiddle/plunkr/jsbin/codepen in order for me to help.

**Comment by Avi-mcqueen** [comment]
Did find solution.
Item in the list is being removed --> refresh is activated, BUT the element is not yet removed from DOM, so it recalculates with original list size. Manual refresh delay solves the problem.
```
$timeout(function(){
            $rootScope.$broadcast('vsRepeatTrigger');
        }, 10);
```
Thank you for help.
