### ISSUE TITLE
cannot use one time data binding when expanding array 

### ISSUE THREAD

**Issue by mato75** [kamilkp/angular-vs-repeat#56]
If I use {{::val}} and I expand the tbody, the data is not updated. Can this be somehow fixed? Because I think using one time data binding here should work.

     <tbody vs-repeat2="28"
       vs-excess="50"
	   vs-offset-after="{{ attrs.offset.bottom }}"
       vs-scroll-parent="window">
	<tr ng-repeat="row in attrs.data.tbody track by $index"
		ng-class="row.theme">
		<td ng-repeat="column in row.data track by $index"
			ng-class="column.theme">
            <div style="display: block" ng-style="{ width: attrs.styles[$index] }">
				<span ng-repeat="val in column.data track by $index"
                                       ng-class="column.themes[$index]">
                               {{::val}}
				</span>
            </div>
		</td>
	</tr>
    </tbody>

**Comment by kamilkp** [comment]
If you use track by $index (in the rows repeater) you cannot use one time binding because ng repeat reuses the same elements. Either use one time binding OR track by $index
