### ISSUE TITLE
maybe use of virtual dom will improve $digest performance

### ISSUE THREAD

**Issue by mato75** [kamilkp/angular-vs-repeat#61]
https://github.com/teropa/angular-virtual-dom

this is the lib I found, will try to evaluate it and if possible use it with this lib, but because this is your project, could you take a look if possible to use your lib with virtual dom.

**Comment by kamilkp** [comment]
From the author's readme:

> angular-virtual-dom supports extensibility using directives - though only with directives that are Virtual DOM aware. That means angular-virtual-dom is not a drop-in substitute for the AngularJS directive compiler, and is meant to be used in limited contexts.

That makes it unusable in a general scenario. vs-repeat is a drop-in plugin (in most cases) and should stay that way
