### ISSUE TITLE
Filters cause gaps

### ISSUE THREAD

**Issue by byronigoe** [kamilkp/angular-vs-repeat#68]
First, let me say that this is an awesome solution to the ng-repeat problem. I think AngularJS should incorporate this as standard behavior.

I use filters with my collection, and I was getting odd behavior when changing those filters. Sometimes there would be gaps, and sometimes elements would be out of order.

In reinitialize(), I added a call to $apply if we've updated the inner collection.
Line 390: if(updateInnerCollection(data)) $scope.$apply();

This seems to fix the problem with gaps, but the console shows "$digest already in progress". Any attempt to fix this new issue (checking $scope.$$phase, or using _.defer) reintroduces the gap problem.

There must be a solution, and I don't think it requires a big change.

**Comment by byronigoe** [comment]
I spent hours trying to fix this the "right" way. For now, I'm using a hack:
_.defer(function() { $scope.$broadcast('vsSetSize-refresh'); });

It seems that the gaps and the mis-ordering might be caused by Angular's tracking, because the problem manifests when the filters remove some but not all of the currently visible elements. Then, when you undo the filter, those elements that remained float to the top.

I tried to eliminate the trackability by creating a new collection object, but my guess is the hash codes match since the elements are the same.

**Comment by GreenTrafficCone** [comment]
I had the same issue using orderBy.  It seems to occur with large datasets (~1000 large objects).
@byronigoe I couldn't get your fix to work sadly.  I got around it by using
```javascript
$timeout(function(){
            $rootScope.$broadcast('vsRepeatTrigger');
        }, 100);
```
Which is mentioned in another issue.  I had to increase the timeout from 10 to 100 for it to make a difference though.

**Comment by osahner** [comment]
Same same. 
Both events 'vsRepeatTrigger' or 'vsSetSize-refresh' work for me.

**Comment by byronigoe** [comment]
For now, vsRepeatTrigger seems like a viable workaround.
