### ISSUE TITLE
RC9 breaks my usage vs. RC5

### ISSUE THREAD

**Issue by dts** [kamilkp/angular-vs-repeat#80]
Bower upgraded me automatically to RC9, which causes the "window" (the visible items) to move down faster than the "viewport" (where I'm actually looking).  I'm not sure what changes happen, and I don't have the time to debug it at the moment (RC5 works perfectly for my purposes, so I've just locked it down), but I thought I'd report the issue just so it's publicly visible.

**Comment by kamilkp** [comment]
Beta.1 no longer uses mousewheeling hacks. Check out the new version
