### ISSUE TITLE
position:absolute; .vs-repeat-repeated-element 

### ISSUE THREAD

**Issue by leblancmeneses** [kamilkp/angular-vs-repeat#84]
I am using flexbox to position ng-repeated items so they nicely wrap across the screen.

```
.flex-list {
	display: flex;
	flex-flow: row wrap;
	align-items: center;
	justify-content: space-between;
}

.Media {
	width: 325px;
	height: 115px;
	display: flex;
	align-items: flex-start;
	box-shadow: 0px 11px 12px -14px rgba(0,0,0,0.75);
}
```

When integrating this lib into my project I noticed .vs-repeat-repeated-element   has position:absolute that overrides my flexbox definition.

Why is position: absolute necessary?   Is there a property that allows me to specify page size.  Example I can calculate how many items should be rendered in the  vs-repeat viewport.  vs-repeat-page-size=40

**Comment by kensplanet** [comment]
Same for me. the position:absolute is messing up my table.

**Comment by kamilkp** [comment]
This has been completely redone in beta.1. Also check out http://kamilkp.github.io/angular-vs-repeat/#?tab=9 to see working tables. angular-vs-repeat no longer uses position absolute on repeated elements!
