### ISSUE TITLE
How to display length of filtered ng-repeat data?

### ISSUE THREAD

**Issue by daysv** [kamilkp/angular-vs-repeat#85]
```html
<div ng-repeat="person in filtered = (data | filter: query)">
</div>
<div>{{filtered .length}}</div>
```
I can display the length of filtered ng-repeat data in angular.
But the variable is $vs_collection instead of filtered in vs-repeat.
How to display it?

**Comment by tcdevs** [comment]
Check my early issue #6 for the solution. Hope that helps.

**Comment by daysv** [comment]
@tcdevs thanks
