### ISSUE TITLE
bower version is only 1.0.0-rc9

### ISSUE THREAD

**Issue by jamesbrobb** [kamilkp/angular-vs-repeat#88]
I'm using bower to install angular-vs-repeat, but the current version is 1.0.0-rc9, which introduces issue #80.

Please can you update the bower version to 1.0.0-rc13, thanks.

**Comment by kamilkp** [comment]
updated to beta.1

**Comment by jamesbrobb** [comment]
bower update/install is now giving me bower.json

`"version": "1.0.0-rc9"`

and the header for the js is saying it's rc8

`//
// Copyright Kamil Pękala http://github.com/kamilkp
// Angular Virtual Scroll Repeat v1.0.0-rc8 2015/05/29
//`

**Comment by kamilkp** [comment]
Well, there is a tag https://github.com/kamilkp/angular-vs-repeat/releases/tag/v1.0.0-beta.1 <https://github.com/kamilkp/angular-vs-repeat/releases/tag/v1.0.0-beta.1> like it should be. Ain’t that enough for bower?

**Comment by jamesbrobb** [comment]
Not sure to be honest. But it doesn't appear to be. I've tried to force it to v1.0.0-beta.1 but it just gives me 1.0.0-rc9
