### ISSUE TITLE
Broke when using on tables

### ISSUE THREAD

**Issue by diego-vieira** [kamilkp/angular-vs-repeat#9]
I have tried using it on a table, but it didn't worked.
```
<tbody vs-repeat>
<tr ng-repeat..
```

Is this a known issue or?
Thanks

**Comment by tamlyn** [comment]
I think the problem is that as soon as you set `position: absolute` on the table rows, you lose the columns.

**Comment by CristianMR** [comment]
@tamlyn that's right. Today I started with one task, and I'm trying to do a infinite scroll in a table, and ```css position: absolute``` broke all the styles of columns. Then, if you set the position to relative, you have a problem because the style ```css transform: translateY(486px);``` separate the rows like ```css margin-bottom: 'your-row-height'px;```.

**Comment by jetpackjarrett** [comment]
I'm also having this problem. Any ideas on how to make this cooperate with tables?

**Comment by CristianMR** [comment]
@jetpackjarrett my first approach was watch the width in every column, then assign with ng-style to the corresponding row column cell, doing use of directives.

So, you could think that I'm doing abuse of watchers but, in my case there is only ten rows at the same time.

The second thing, time after, down the </table> I did an ng-repeat of divs. Because the amount of problems about using table rows.

```js
function thWidth($window:angular.IWindowService){
    return {
      restrict: 'A',
      scope: {
        thWidth: '='
      },
      link: function(scope, element, attrs){

        scope.$watch(function() {
          return element.context.clientWidth;
        }, function(newValue, oldValue){
          if(newValue === oldValue) return;
          scope.thWidth = newValue;
        });

       // lodash function (not refresh more than 10 times per second)
        var resize = _.throttle(function(){
            scope.$evalAsync(function() {
                scope.thWidth = element.context.clientWidth;
            });
        }, 100);
        
        angular.element($window).bind("resize", function(){
            resize();  
        });    
      }
    }
  }

angular.module(cookies).directive('thWidth');
```

**Comment by Prashant31** [comment]
Does anybody found a solution for it??

**Comment by kamilkp** [comment]
Working now in beta.1
See: http://kamilkp.github.io/angular-vs-repeat/#?tab=9
