### ISSUE TITLE
Infinite-Scroll - Feature request.

### ISSUE THREAD

**Issue by graphefruit** [kamilkp/angular-vs-repeat#93]
Hello, 
first of all: thanks for this great plugin.
I'd have a special feature request: Infinite scroll.

I would need a feature where the array can be updated and the scroll is still working.
I tried to update the array with the actual plugin, but the content is never shown, and I always get the initial array-values to see, even if the array is passed with 100-Items.

Reference: https://material.angularjs.org/latest/demo/virtualRepeat -> Infinite Scroll.

The problem is that angular material, cant calculate the item-size. This plugin can do this and thats awesome!

Greetings
Graphefruit

**Comment by ribeirobreno** [comment]
Works here. Was this fixed or am i missing something?

**Comment by graphefruit** [comment]
Hi, sorry I forgot this issue. I could fix it because I one way bound my items in the repeat which didn't work.
But the plugin doesn't offer an infinite scroll out of the box.
I needed to write a scroll watcher myself and trigger then a reload of the data.

**Comment by kamilkp** [comment]
Yes. It was added recently see https://github.com/kamilkp/angular-vs-repeat/blob/master/CHANGELOG.md

`vs-scrolled-to-end` hook

Kamil Pękala

Dnia 07.03.2016 o godz. 17:55 Breno Ribeiro <notifications@github.com> napisał(a):
