### ISSUE TITLE
1.0.0-beta.1 no longer works

### ISSUE THREAD

**Issue by jamesbrobb** [kamilkp/angular-vs-repeat#94]
I've just explicitly updated another library through bower, but bower also decided to automatically update angular-vs-repeat back to version rc9 (due to the issue described in #88).

I then manually reinstalled 1.0.0-beta.1 (using `bower install angular-vs-repeat#1.0.0-beta.1`) but this is no longer the previous version of 1.0.0-beta.1 that was working as expected. But is what appears to be a complete re-write of how the component works, which i'm unable to get working?

Is this new version replacing the old 1.0.0-beta.1?

Thanks.

**Comment by kamilkp** [comment]
No. I'm not rewriting old versions. A new version always gets a new incremented version number.

Kamil Pękala

Dnia 14.12.2015 o godz. 17:56 James Robb <notifications@github.com> napisał(a):

**Comment by jamesbrobb** [comment]
I can only presume - due to the fact you're obviously yet to master bower -
that the version of 1.0.0-beta.1 you instructed me to download a couple of
weeks ago, was not in fact that new version. Because I was able to drop
that version straight into an existing project with no issues.

Is 1.0.0-beta.1 a drop in replacement for the previous rc version? As in,
it should just work with existing code?

**Comment by kamilkp** [comment]
Yes it should. Can you make a jsfiddle that works with the last rc version and not beta.1 ?

Kamil Pękala

Dnia 14.12.2015 o godz. 20:10 James Robb <notifications@github.com> napisał(a):

> I can only presume - due to the fact you're obviously yet to master bower -
> that the version of 1.0.0-beta.1 you instructed me to download a couple of
> weeks ago, was not in fact that new version. Because I was able to drop
> that version straight into an existing project with no issues.
> 
> Is 1.0.0-beta.1 a drop in replacement for the previous rc version? As in,
> it should just work with existing code?

**Comment by igor9silva** [comment]
@kamilkp I've also noted that all minified version do still in RC12.
i.e. Beta1 and Beta0 releases have minified file as RC12, at least it's initial comment says RC12

**Comment by kamilkp** [comment]
Try bower install now. There was a problem with semver. You should get a 1.0.1-beta version

Kamil Pękala

Dnia 15.12.2015 o godz. 13:39 Igor Silva <notifications@github.com> napisał(a):

**Comment by igor9silva** [comment]
Thanks @kamilkp, everything seems ok now. Great directive, I've improved ionic's performance a lot within it!
