### ISSUE TITLE
Scrolling Down works fine, when I scroll up, it scrolls me all the way to the top and doesn't stop

### ISSUE THREAD

**Issue by c5racing** [kamilkp/angular-vs-repeat#95]
I'm using vs-repeat as in <tbody vs-repeat vs-scroll-parent="window">

It works great when I scroll down using Page Down or my mouse (Using Chrome on Windows); however, when scrolling up, if I click Page Up or use my mouse, it continues scrolling all the way to the top of the page.

Any suggestions on where to look?

**Comment by c5racing** [comment]
It appears this only behaves this way when I don't use track by $index in my ng-repeat.  If I use track by item.ItemId, or no track by at all, this is when it occurs.

**Comment by msarsha** [comment]
I am having the same issue, track by $index did not help.
Scroll up works - scroll down will scroll to the bottom.
