### ISSUE TITLE
Help with Horizontal Scrolling

### ISSUE THREAD

**Issue by robhicks** [kamilkp/angular-vs-repeat#96]
How does horizontal scrolling work? Are there any docs? 

I have looked at the example but can't get it to work correctly. It seems the vs-repeat-before-content element added before the repeated items pushes the repeated items down. While that can easily fixed with css, the repeated elements scroll off to the left rather than staying in the repeat container.

Here's a [plunker](http://plnkr.co/edit/XHshiT5a3Y5u9YoyBQh9?p=preview) showing what I'm seeing.

**Comment by robhicks** [comment]
I have figured it out.

**Comment by dzek69** [comment]
And you decided not to share your solution. Thanks :(
