### ISSUE TITLE
is it possible to control startIndex programatticaly?

### ISSUE THREAD

**Issue by aharbick** [kamilkp/angular-vs-repeat#99]
I'm using a vs-repeat something like this:

```
<div vs-repeat>
  <div ng-repeat="item in items track by $index">
   ...
  </div>
</div>
```

I have UI functionality that when you click on a specific item it renders a different view (details for the item).  When I close the details for the item a vsRepeatReinitialized event fires and sets startIndex to 0.

So...  If my list of items is many items long and the viewport is small the effect is that I scroll through dozens of items, click on one of them, close the details, and then end up at the top of the list only to need to scroll again.

If I have the desired startIndex is there a way that I can have vs-repeat start by showing items AT that index?

**Comment by aharbick** [comment]
A couple of complicating factors (which could be confounding)
 1. The click to get details uses HTML5 pushState.
 2. I've got infinitescroll wired into the vs-repeat with an index watcher as suggested here: https://github.com/kamilkp/angular-vs-repeat/issues/10#issuecomment-55221981

**Comment by dpaquette** [comment]
I am also looking for the ability to set the `startIndex` for a very similar use case

**Comment by kamilkp** [comment]
You can do it by scrolling the container manually via javascript to a previously stored value. I don't want to overload the lib with functionalities that can be achieved by an external code/directive

**Comment by aharbick** [comment]
Sorry I didn't ask clearly enough.  I'm fine saving the startIndex and then scrolling to that index, but I don't know how to do that with vs-repeat if the element I wish to scroll to is not currently in the DOM (sorry if that's a dumb question).  Thanks for building a really helpful lib.
